#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClassSelect

#include "Basic.hpp"

#include "ClassSelect_classes.hpp"
#include "ClassSelect_parameters.hpp"


namespace SDK
{

// Function ClassSelect.ClassSelect_C.ExecuteUbergraph_ClassSelect
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UClassSelect_C::ExecuteUbergraph_ClassSelect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClassSelect_C", "ExecuteUbergraph_ClassSelect");

	Params::ClassSelect_C_ExecuteUbergraph_ClassSelect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ClassSelect.ClassSelect_C.PlayOpenAnimation
// (Event, Public, BlueprintEvent)

void UClassSelect_C::PlayOpenAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClassSelect_C", "PlayOpenAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ClassSelect.ClassSelect_C.MoveToCustomizingEvent
// (Event, Public, BlueprintEvent)

void UClassSelect_C::MoveToCustomizingEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClassSelect_C", "MoveToCustomizingEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ClassSelect.ClassSelect_C.MoveToCharacterSelectEvent
// (Event, Public, BlueprintEvent)

void UClassSelect_C::MoveToCharacterSelectEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClassSelect_C", "MoveToCharacterSelectEvent");

	UObject::ProcessEvent(Func, nullptr);
}

}

