#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Connecting_Login

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Connecting_Login.Connecting_Login_C
// 0x0008 (0x0320 - 0x0318)
class UConnecting_Login_C final : public UMM_Connecting_Login
{
public:
	class UWidgetAnimation*                       Ani_Loop;                                          // 0x0318(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Connecting_Login_C">();
	}
	static class UConnecting_Login_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConnecting_Login_C>();
	}
};
static_assert(alignof(UConnecting_Login_C) == 0x000008, "Wrong alignment on UConnecting_Login_C");
static_assert(sizeof(UConnecting_Login_C) == 0x000320, "Wrong size on UConnecting_Login_C");
static_assert(offsetof(UConnecting_Login_C, Ani_Loop) == 0x000318, "Member 'UConnecting_Login_C::Ani_Loop' has a wrong offset!");

}

