#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_Save

#include "Basic.hpp"

#include "Customizing_Save_classes.hpp"
#include "Customizing_Save_parameters.hpp"


namespace SDK
{

// Function Customizing_Save.Customizing_Save_C.CreateSaveSlot
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UMM_Customizing_SaveSlot*> ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, ContainsInstancedReference)

TArray<class UMM_Customizing_SaveSlot*> UCustomizing_Save_C::CreateSaveSlot(int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Customizing_Save_C", "CreateSaveSlot");

	Params::Customizing_Save_C_CreateSaveSlot Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

