#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_Category

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Customizing_Category.Customizing_Category_C
// 0x0000 (0x0328 - 0x0328)
class UCustomizing_Category_C final : public UMM_Customizing_Category
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Customizing_Category_C">();
	}
	static class UCustomizing_Category_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCustomizing_Category_C>();
	}
};
static_assert(alignof(UCustomizing_Category_C) == 0x000008, "Wrong alignment on UCustomizing_Category_C");
static_assert(sizeof(UCustomizing_Category_C) == 0x000328, "Wrong size on UCustomizing_Category_C");

}

