#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_Palette_3

#include "Basic.hpp"

#include "Customizing_Palette_3_classes.hpp"
#include "Customizing_Palette_3_parameters.hpp"


namespace SDK
{

// Function Customizing_Palette_3.Customizing_Palette_3_C.ExecuteUbergraph_Customizing_Palette_3
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCustomizing_Palette_3_C::ExecuteUbergraph_Customizing_Palette_3(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Customizing_Palette_3_C", "ExecuteUbergraph_Customizing_Palette_3");

	Params::Customizing_Palette_3_C_ExecuteUbergraph_Customizing_Palette_3 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Customizing_Palette_3.Customizing_Palette_3_C.CreatePaletteItem
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UMM_Customizing_PaletteItem*>ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, ContainsInstancedReference)

TArray<class UMM_Customizing_PaletteItem*> UCustomizing_Palette_3_C::CreatePaletteItem(int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Customizing_Palette_3_C", "CreatePaletteItem");

	Params::Customizing_Palette_3_C_CreatePaletteItem Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Customizing_Palette_3.Customizing_Palette_3_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCustomizing_Palette_3_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Customizing_Palette_3_C", "PreConstruct");

	Params::Customizing_Palette_3_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

