#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_Save

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Customizing_Save.Customizing_Save_C
// 0x0000 (0x0378 - 0x0378)
class UCustomizing_Save_C final : public UMM_Customizing_Save
{
public:
	TArray<class UMM_Customizing_SaveSlot*> CreateSaveSlot(int32 Count);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Customizing_Save_C">();
	}
	static class UCustomizing_Save_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCustomizing_Save_C>();
	}
};
static_assert(alignof(UCustomizing_Save_C) == 0x000008, "Wrong alignment on UCustomizing_Save_C");
static_assert(sizeof(UCustomizing_Save_C) == 0x000378, "Wrong size on UCustomizing_Save_C");

}

