#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_ComponentTitle

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Customizing_ComponentTitle.Customizing_ComponentTitle_C
// 0x0000 (0x02F8 - 0x02F8)
class UCustomizing_ComponentTitle_C final : public UMM_Customizing_ComponentTitle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Customizing_ComponentTitle_C">();
	}
	static class UCustomizing_ComponentTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCustomizing_ComponentTitle_C>();
	}
};
static_assert(alignof(UCustomizing_ComponentTitle_C) == 0x000008, "Wrong alignment on UCustomizing_ComponentTitle_C");
static_assert(sizeof(UCustomizing_ComponentTitle_C) == 0x0002F8, "Wrong size on UCustomizing_ComponentTitle_C");

}

