#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_Palette_Item

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Customizing_Palette_Item.Customizing_Palette_Item_C
// 0x0000 (0x0318 - 0x0318)
class UCustomizing_Palette_Item_C final : public UMM_Customizing_PaletteThumbnail
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Customizing_Palette_Item_C">();
	}
	static class UCustomizing_Palette_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCustomizing_Palette_Item_C>();
	}
};
static_assert(alignof(UCustomizing_Palette_Item_C) == 0x000008, "Wrong alignment on UCustomizing_Palette_Item_C");
static_assert(sizeof(UCustomizing_Palette_Item_C) == 0x000318, "Wrong size on UCustomizing_Palette_Item_C");

}

