#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Customizing_Scroll_Item

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Customizing_Scroll_Item.Customizing_Scroll_Item_C
// 0x0000 (0x0330 - 0x0330)
class UCustomizing_Scroll_Item_C final : public UMM_Customizing_ListItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Customizing_Scroll_Item_C">();
	}
	static class UCustomizing_Scroll_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCustomizing_Scroll_Item_C>();
	}
};
static_assert(alignof(UCustomizing_Scroll_Item_C) == 0x000008, "Wrong alignment on UCustomizing_Scroll_Item_C");
static_assert(sizeof(UCustomizing_Scroll_Item_C) == 0x000330, "Wrong size on UCustomizing_Scroll_Item_C");

}

