#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultFilter

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DefaultFilter.DefaultFilter_C
// 0x0000 (0x0050 - 0x0050)
class UDefaultFilter_C final : public UMM_NavigationQueryFilter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DefaultFilter_C">();
	}
	static class UDefaultFilter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefaultFilter_C>();
	}
};
static_assert(alignof(UDefaultFilter_C) == 0x000008, "Wrong alignment on UDefaultFilter_C");
static_assert(sizeof(UDefaultFilter_C) == 0x000050, "Wrong size on UDefaultFilter_C");

}

