#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FadeUI

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FadeUI.FadeUI_C
// 0x0008 (0x0328 - 0x0320)
class UFadeUI_C final : public UFadeWidget
{
public:
	class UImage*                                 FadeImg;                                           // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FadeUI_C">();
	}
	static class UFadeUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFadeUI_C>();
	}
};
static_assert(alignof(UFadeUI_C) == 0x000008, "Wrong alignment on UFadeUI_C");
static_assert(sizeof(UFadeUI_C) == 0x000328, "Wrong size on UFadeUI_C");
static_assert(offsetof(UFadeUI_C, FadeImg) == 0x000320, "Member 'UFadeUI_C::FadeImg' has a wrong offset!");

}

