#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Level_Logo_LevelInstance_1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Level_Logo_LevelInstance_1.Level_Logo_C
// 0x0008 (0x0228 - 0x0220)
class ALevel_Logo_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Level_Logo(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Level_Logo_C">();
	}
	static class ALevel_Logo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALevel_Logo_C>();
	}
};
static_assert(alignof(ALevel_Logo_C) == 0x000008, "Wrong alignment on ALevel_Logo_C");
static_assert(sizeof(ALevel_Logo_C) == 0x000228, "Wrong size on ALevel_Logo_C");
static_assert(offsetof(ALevel_Logo_C, UberGraphFrame) == 0x000220, "Member 'ALevel_Logo_C::UberGraphFrame' has a wrong offset!");

}

