#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LogoMediaWidget

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LogoMediaWidget.LogoMediaWidget_C
// 0x0000 (0x0348 - 0x0348)
class ULogoMediaWidget_C final : public ULogoMediaWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LogoMediaWidget_C">();
	}
	static class ULogoMediaWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULogoMediaWidget_C>();
	}
};
static_assert(alignof(ULogoMediaWidget_C) == 0x000008, "Wrong alignment on ULogoMediaWidget_C");
static_assert(sizeof(ULogoMediaWidget_C) == 0x000348, "Wrong size on ULogoMediaWidget_C");

}

