#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mode_Unified

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mode_Unified.Mode_Unified_C
// 0x0010 (0x04C0 - 0x04B0)
class AMode_Unified_C final : public AMM_UnifiedGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mode_Unified_C">();
	}
	static class AMode_Unified_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMode_Unified_C>();
	}
};
static_assert(alignof(AMode_Unified_C) == 0x000010, "Wrong alignment on AMode_Unified_C");
static_assert(sizeof(AMode_Unified_C) == 0x0004C0, "Wrong size on AMode_Unified_C");
static_assert(offsetof(AMode_Unified_C, DefaultSceneRoot) == 0x0004B0, "Member 'AMode_Unified_C::DefaultSceneRoot' has a wrong offset!");

}

