#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OneStoreIap

#include "Basic.hpp"

#include "OneStoreIap_classes.hpp"
#include "OneStoreIap_parameters.hpp"


namespace SDK
{

// Function OneStoreIap.OneStoreBlueprintFunctionLibrary.OneStoreDisconnect
// (Final, Native, Static, Private, BlueprintCallable)

void UOneStoreBlueprintFunctionLibrary::OneStoreDisconnect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreBlueprintFunctionLibrary", "OneStoreDisconnect");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function OneStoreIap.OneStoreBlueprintFunctionLibrary.OneStorePurchaseVerify
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// class FString                           PublicKey                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           OriginalPurchaseData                                   (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           SignatureData                                          (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UOneStoreBlueprintFunctionLibrary::OneStorePurchaseVerify(const class FString& PublicKey, const class FString& OriginalPurchaseData, const class FString& SignatureData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreBlueprintFunctionLibrary", "OneStorePurchaseVerify");

	Params::OneStoreBlueprintFunctionLibrary_OneStorePurchaseVerify Parms{};

	Parms.PublicKey = std::move(PublicKey);
	Parms.OriginalPurchaseData = std::move(OriginalPurchaseData);
	Parms.SignatureData = std::move(SignatureData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreBlueprintFunctionLibrary.OneStoreShowMessage
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// class FString                           Title                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           Message                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UOneStoreBlueprintFunctionLibrary::OneStoreShowMessage(const class FString& Title, const class FString& Message)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreBlueprintFunctionLibrary", "OneStoreShowMessage");

	Params::OneStoreBlueprintFunctionLibrary_OneStoreShowMessage Parms{};

	Parms.Title = std::move(Title);
	Parms.Message = std::move(Message);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function OneStoreIap.OneStoreIapAcknowledgePurchaseFunction.OneStoreIapAcknowledgePurchase
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           PurchaseData                                           (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           DevPayload                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapAcknowledgePurchaseFunction*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapAcknowledgePurchaseFunction* UOneStoreIapAcknowledgePurchaseFunction::OneStoreIapAcknowledgePurchase(class UObject* WorldContextObject, const class FString& PurchaseData, const class FString& DevPayload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapAcknowledgePurchaseFunction", "OneStoreIapAcknowledgePurchase");

	Params::OneStoreIapAcknowledgePurchaseFunction_OneStoreIapAcknowledgePurchase Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.PurchaseData = std::move(PurchaseData);
	Parms.DevPayload = std::move(DevPayload);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapBPLibrary.OneStoreIapSampleFunction
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// float                                   Param                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UOneStoreIapBPLibrary::OneStoreIapSampleFunction(float Param)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapBPLibrary", "OneStoreIapSampleFunction");

	Params::OneStoreIapBPLibrary_OneStoreIapSampleFunction Parms{};

	Parms.Param = Param;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapConsumePurchaseFunction.OneStoreIapConsumePurchase
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           PurchaseData                                           (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           DevPayload                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapConsumePurchaseFunction*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapConsumePurchaseFunction* UOneStoreIapConsumePurchaseFunction::OneStoreIapConsumePurchase(class UObject* WorldContextObject, const class FString& PurchaseData, const class FString& DevPayload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapConsumePurchaseFunction", "OneStoreIapConsumePurchase");

	Params::OneStoreIapConsumePurchaseFunction_OneStoreIapConsumePurchase Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.PurchaseData = std::move(PurchaseData);
	Parms.DevPayload = std::move(DevPayload);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapGetPurchaseFunction.OneStoreIapPurchaseInfo
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ProductType                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapGetPurchaseFunction*  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapGetPurchaseFunction* UOneStoreIapGetPurchaseFunction::OneStoreIapPurchaseInfo(class UObject* WorldContextObject, const class FString& ProductType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapGetPurchaseFunction", "OneStoreIapPurchaseInfo");

	Params::OneStoreIapGetPurchaseFunction_OneStoreIapPurchaseInfo Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ProductType = std::move(ProductType);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapGetStoreCodeFunction.OneStoreIapGetStoreCode
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapGetStoreCodeFunction* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapGetStoreCodeFunction* UOneStoreIapGetStoreCodeFunction::OneStoreIapGetStoreCode(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapGetStoreCodeFunction", "OneStoreIapGetStoreCode");

	Params::OneStoreIapGetStoreCodeFunction_OneStoreIapGetStoreCode Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapManageRecurringFunction.OneStoreIapManageRecurring
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           PurchaseData                                           (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapManageRecurringFunction*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapManageRecurringFunction* UOneStoreIapManageRecurringFunction::OneStoreIapManageRecurring(class UObject* WorldContextObject, const class FString& PurchaseData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapManageRecurringFunction", "OneStoreIapManageRecurring");

	Params::OneStoreIapManageRecurringFunction_OneStoreIapManageRecurring Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.PurchaseData = std::move(PurchaseData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapProductDetailsFunction.OneStoreIapGetProductDetails
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ProductType                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class FString>                   ProductList                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UOneStoreIapProductDetailsFunction*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapProductDetailsFunction* UOneStoreIapProductDetailsFunction::OneStoreIapGetProductDetails(class UObject* WorldContextObject, const class FString& ProductType, const TArray<class FString>& ProductList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapProductDetailsFunction", "OneStoreIapGetProductDetails");

	Params::OneStoreIapProductDetailsFunction_OneStoreIapGetProductDetails Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ProductType = std::move(ProductType);
	Parms.ProductList = std::move(ProductList);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapRequestLoginFunction.OneStoreIapRequestLogin
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapRequestLoginFunction* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapRequestLoginFunction* UOneStoreIapRequestLoginFunction::OneStoreIapRequestLogin(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapRequestLoginFunction", "OneStoreIapRequestLogin");

	Params::OneStoreIapRequestLoginFunction_OneStoreIapRequestLogin Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapRequestPurchaseFunction.OneStoreIapRequestPurchase
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ProductType                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ProductId                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ProductName                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           DevPayload                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapRequestPurchaseFunction*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapRequestPurchaseFunction* UOneStoreIapRequestPurchaseFunction::OneStoreIapRequestPurchase(class UObject* WorldContextObject, const class FString& ProductType, const class FString& ProductId, const class FString& ProductName, const class FString& DevPayload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapRequestPurchaseFunction", "OneStoreIapRequestPurchase");

	Params::OneStoreIapRequestPurchaseFunction_OneStoreIapRequestPurchase Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ProductType = std::move(ProductType);
	Parms.ProductId = std::move(ProductId);
	Parms.ProductName = std::move(ProductName);
	Parms.DevPayload = std::move(DevPayload);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function OneStoreIap.OneStoreIapRequestUpdateFunction.OneStoreIapRequestUpdate
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UOneStoreIapRequestUpdateFunction*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UOneStoreIapRequestUpdateFunction* UOneStoreIapRequestUpdateFunction::OneStoreIapRequestUpdate(class UObject* WorldContextObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("OneStoreIapRequestUpdateFunction", "OneStoreIapRequestUpdate");

	Params::OneStoreIapRequestUpdateFunction_OneStoreIapRequestUpdate Parms{};

	Parms.WorldContextObject = WorldContextObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

