#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VolumeController

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass VolumeController.VolumeController_C
// 0x0000 (0x0328 - 0x0328)
class UVolumeController_C final : public UMM_VolumeController
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VolumeController_C">();
	}
	static class UVolumeController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVolumeController_C>();
	}
};
static_assert(alignof(UVolumeController_C) == 0x000008, "Wrong alignment on UVolumeController_C");
static_assert(sizeof(UVolumeController_C) == 0x000328, "Wrong size on UVolumeController_C");

}

