#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_Master

#include "Basic.hpp"

#include "MirMobile_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_Master.Widget_Master_C
// 0x0000 (0x0320 - 0x0320)
class UWidget_Master_C final : public UMM_Widget_Master
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Widget_Master_C">();
	}
	static class UWidget_Master_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_Master_C>();
	}
};
static_assert(alignof(UWidget_Master_C) == 0x000008, "Wrong alignment on UWidget_Master_C");
static_assert(sizeof(UWidget_Master_C) == 0x000320, "Wrong size on UWidget_Master_C");

}

